simplesurvey/simplesurvey/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey.urls')),
]

simplesurvey/survey/urls.py
from django.urls import path
from . import views


urlpatterns =patterns('',
  path('', views.index, name="root"),
  path('survey_load/', views.load_survey, name="load-survey"),
  path('survey/(?P<survey_id>\d+)/', views.survey_view, name="survey-detail"),
  path('admin_login/', views.admin_login, name="admin-login"),
  path('admin_panel/', views.admin_panel, name="admin-panel"),
  path('admin_panel/survey_delete/', views.survey_delete, name="admin-survey-delete"),
  path('admin_panel/survey/(?P<survey_id>\d+)/', views.admin_answers, name="answer-detail"),
  path('admin_panel/survey_create_view/', views.survey_create_view, name="admin-survey-create-view"),
  path('admin_panel/survey_create/', views.survey_create, name="admin-survey-create"),
  path('admin_panel/question_add_view/', views.question_add_view, name="admin-question-add-view"),
  path('admin_panel/question_add/', views.question_add, name="admin-question-add"),
  path('admin_panel/choice_add_view/', views.choice_add_view, name="admin-choice-add-view"),
  path('admin_panel/choice_add/', views.choice_add, name="admin-choice-add"),
  path('admin_panel/survey_delete/', views.survey_delete, name="admin-survey-delete"),
)

simplesurvey/survey/models.py
from django.db import models

# Create your models here.
class Survey(models.Model):
  title = models.CharField(max_length = 300)

class Question(models.Model):
  question_text = models.CharField(max_length = 900)
  survey = models.ForeignKey(Survey, on_delete=models.CASCADE)

class Choice(models.Model):
  choice_text = models.CharField(max_length = 900)
  question = models.ForeignKey(Question, on_delete=models.CASCADE) 

class SurveyAnswer(models.Model):
  orig_survey= models.ForeignKey(Survey, on_delete=models.CASCADE)  

class QuestionAnswer(models.Model):
  answer = models.ForeignKey(Choice, on_delete=models.CASCADE)
  survey_answer = models.ForeignKey(SurveyAnswer, on_delete=models.CASCADE)

simplesurvey/survey/views.py
from django.shortcuts import render, redirect
from .models import Survey, SurveyAnswer, Question, Choice, QuestionAnswer
from django.contrib.auth import authenticate, login
# Create your views here.
def index(request):
  ctx = {}
  return render(request,'main.html', ctx)

def survey_view(request, survey_id = None):
  try:
    survey = Survey.objects.get(id=survey_id)
    questions = survey.question_set.all()
    ctx = {'survey': survey, 'questions': questions}
  except: 
    return render(request, 'surveynotfound-error.html', {'sv_id': survey_id})
  return render(request, 'survey-take.html',ctx)   
    

def load_survey(request):
  sv_to_load = request.POST['survey_view']
  return redirect('survey-detail', survey_id = sv_to_load)

def survey_fill(request):
   answer = SurveyAnswer()
   orig_survey = Survey.objects.get(id=request.POST['survey_id'])
   answer.orig_survey = orig_survey
   answer.save()
   questions = orig_survey.question_set.all()
   for question in questions:
     question_post = request.POST['question'+str(question.id)]
     QA = QuestionAnswer()
     QA.answer.answer = Choice.objects.get(id=int(question_post))
     QA.survey_answer = answer
     QA.save()
   answer.save()
   return render(request,'survey-complete.html', {})   

def admin_login(request): 
  admin_username = request.POST['username']
  admin_password = request.POST['password']
  user = authenticate(username=admin_username, password=admin_password)
  if user is not None:
    login(request, user)
    return redirect('admin-panel')
  return render(request, 'main.html', {'login': False})   

def admin_panel(request):
    surveys = Survey.objects.all()
    ctx = {'surveys': surveys}
    return render(request, 'admin-panel.html', ctx)

def survey_delete(request):
  survey_deletion = request.POST['sv_delete']
  sv_del = Survey.objects.get(id=int(survey_deletion))
  sv_del.delete()
  return redirect('admin-panel')

def admin_answers(request, survey_id):
  survey = Survey.objects.get(id=survey_id)
  answers = survey.surveyanswer_set.all()
  ctx = {'answers': answers, 'survey':survey}
  return render(request, 'admin-survey-detail.html', ctx)

def survey_create_view(request):
  return render(request, 'survey-create.html',{})

def question_add_view(request):
  return render(request, 'question-add.html',{})

def choice_add_view(request):
  question = Question.objects.get(id=int(request.session['current_question']))
  return render(request, 'choice-add.html',{'question':question})

def survey_create(request):
  newSurvey = Survey()
  newSurvey.title = request.POST['survey_title']
  newSurvey.save()
  request.session['current_survey'] = newSurvey.id
  return redirect('admin-question-add-view')

def question_add(request):
   survey_add = Survey.objects.get(id=int(request.session['current_survey']))
   new_question = Question()
   new_question.question_text = request.POST['question_text']
   survey_add.question_set.add(new_question)
   new_question.save()
   survey_add.save()
   request.session['current_question'] = new_question.id
   return redirect('admin-choice-add-view')

def choice_add(request):
   question = Question.objects.get(id=int(request.session['current_question']))
   newChoice =  Choice()
   newChoice.choice_text = request.POST['choice_text']
   question.choice_set.add(newChoice)
   newChoice.save()
   question.save()
   return redirect('admin-choice-add-view')  




 

simplesurvey/survey/templates/admin-panel.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  
  </style>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class= "container-fluid">
      <div class ="navbar-header">
        <a class = "navbar-brand" href={% 'root' %}>Survey Site</a>
      </div>
      <ul class = "nav navbar-nav navbar-right">
        <li><a href={% url 'admin-survey-create-view' %}>Create Survey</a></li>
        <li><a href="#">View Survey Data</a></li>
      </ul>
    </div>
  </div>
  <div class= "centerdv container">
    <div class="page-header">
      <h2>Survey Results</h2>
    </div>
    <div class= "panel panel-default">
      <table class="table">
        <thead>
          <tr>
            <th>Survey ID#</th>
            <th>Survey Title</th>
            <th>Answers</th>
            <th>Delete Survey</th>   
          </tr>
        </thead>
        <tbody>
          {% for survey in surveys %}
          <tr>
            <td>{{survey.id}}</td>
            <td>{{survey.title}}</td>
            <td><a class="btn btn-primary" href={% url 'answer-detail' survey.id %}>View Answer</a></td>
            <td>
              <form method= "post" {% url 'admin-survey-delete' %}>
                {% csrf_token %}
                <input type = "hidden" name="sv-delete" value= {{survey.id}}>
                <input type = "submit" class = "btn btn-danger" value= "Delete Survey">
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>  
</body>
</html>

simplesurvey/survey/templates/admin-survey-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  
  </style>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class= "container-fluid">
      <div class ="navbar-header">
        <a class = "navbar-brand" href={% 'root' %}>Survey Site</a>
      </div>
      <ul class = "nav navbar-nav navbar-right">
        <li><a href={% url 'admin-survey-create-view' %}>Create Survey</a></li>
        <li><a href="{% url 'admin-panel' %}">View Survey Data</a></li>
      </ul>
    </div>
  </div>
  <div class= "centerdv container">
    <div class="page-header">
      <h2>{{survey.title}}</h2>
    </div>
    <div class= "panel panel-default">
      <table class="table">
        <thead>
          <tr>
            <th>Question ID#</th>
            <th>Question Title</th>
            <th>Answer</th>  
          </tr>
        </thead>
        <tbody>
          {% for answer in answers %}
          {% for qa in answer.questionanswer_set.all %}
          <tr>
            <td>{{qa.answer.question.id}}</td>
            <td>{{qa.answer.question.question_text}}</td>
            <td>{{qa.answer.choice_text}}</td> 
          </tr>
          {% endfor %}
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>  
</body>
</html>

simplesurvey/survey/templates/choice-add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  .centerform{
    margin-left: auto;
    margin-right: auto;
    width:45%; 
  }
  
  </style>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class= "container-fluid">
      <div class ="navbar-header">
        <a class = "navbar-brand" href={% 'root' %}>Survey Site</a>
      </div>
      <ul class = "nav navbar-nav navbar-right">
        <li><a href={% url 'admin-survey-create-view' %}>Create Survey</a></li>
        <li><a href="{% url 'admin-panel' %}">View Survey Data</a></li>
      </ul>
    </div>
  </div>
  <div class= "centerdv container">
    <div class="page-header">
      <h2>Add a Choice to {{question.question_text}}</h2>
    </div>
    <br>
    <form method= "post" class = "centerform" action = {% url 'admin-choice-add' %}>
      {% csrf_token %}
      <b>Choice Text:</b>
      <input type = "text" class = "form-control" name = "choice_text">
      <br>
      <input type = "submit" class = "btn btn-primary" value = "Add Questions"> 
      <p>
      <a href = {% url 'admin-panel' %} class = "btn btn-success">Finish</a>
      <a href = {% url 'admin-question-add-view' %} class = 'btn btn-primary'>New Question</a>
      </p>
    </form> 
    
  </div>  
</body>
</html> 

simplesurvey/survey/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  .formcss{
    margin-top: 5%;
    margin-bottom: 5%;
    width: 80%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  </style>
  <div class = "jumbotron container centerdv">
    <h1>Simple Survey App</h1>
    <p>Take Surveys here</p>
    <p>
      <a class = "btn btn-primary btn-lg" role="button" data-toggle = "modal" data-target="#surveyIDmodal">Take a Survey</a>
      <a class = "btn btn-info btn-lg" role="button" data-toggle = "modal" data-target="#adminLoginModal">Admin Login</a>

    </p>
  </div>
  <div class = "modal fade" role="dialog" id = "surveyIDmodal">
    <div class = "modal-dialog modal-sm">
      <div class = "modal-content">
        <div class = "modal-header">
          <h4>Enter a survey ID</h4>
        </div>
        <form method = "post" class = "formcss" action ={% url 'load-survey' %}>
          {% csrf_token %}
        <input type = "text" class = "form-control" name = "survey_view"> 
        <br>
        <input type = "submit" class = "btn btn-success " value = "Go!">  
        </form>
      </div>
    </div>
  </div>
  <div class = "modal fade" role="dialog" id = "adminLoginModal">
    <div class = "modal-dialog modal-sm">
      <div class = "modal-content">
        <div class = "modal-header">
          <h4>Login an Admin User</h4>
        </div>
        <form method = "post" class = "formcss" action ={% url 'admin-login' %}>
          {% csrf_token %}
          <b>Username:</b>
        <input type = "text" class = "form-control" name = "username"> 
        <br>
        <b>Password</b>
        <input type = "password" class = "form-control" name= "password">
        <br>
        <input type = "submit" class = "btn btn-success " value = "Login">  
        </form>
      </div>
    </div>
  </div>
</body>
</html>

simplesurvey/survey/templates/question-add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  .centerform{
    margin-left: auto;
    margin-right: auto;
    width:45%; 
  }
  
  </style>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class= "container-fluid">
      <div class ="navbar-header">
        <a class = "navbar-brand" href={% 'root' %}>Survey Site</a>
      </div>
      <ul class = "nav navbar-nav navbar-right">
        <li><a href={% url 'admin-survey-create-view' %}>Create Survey</a></li>
        <li><a href="{% url 'admin-panel' %}">View Survey Data</a></li>
      </ul>
    </div>
  </div>
  <div class= "centerdv container">
    <div class="page-header">
      <h2>Add a question</h2>
    </div>
    <br>
    <form method= "post" class = "centerform" action = {% url 'admin-question-add' %}>
      {% csrf_token %}
      <b>Question:</b>
      <input type = "text" class = "form-control" name = "question_text">
      <br>
      <input type = "submit" class = "btn btn-primary" value = "Complete and Add Choices!"> 
    </form> 
    
  </div>  
</body>
</html> 

simplesurvey/survey/templates/survey-complete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  
  </style>
  <div class="jumbotron container centerdv">
    <h1>Survey Complete!</h1>
    <br>
    <a class = "btn btn-info btn-lg" role = "button" href= {% url 'root' %}>Return to the Main Page!</a>
  </div>
</body>
</html>

simplesurvey/survey/templates/survey-create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  .centerform{
    margin-left: auto;
    margin-right: auto;
    width:45%; 
  }
  
  </style>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class= "container-fluid">
      <div class ="navbar-header">
        <a class = "navbar-brand" href={% 'root' %}>Survey Site</a>
      </div>
      <ul class = "nav navbar-nav navbar-right">
        <li><a href={% url 'admin-survey-create-view' %}>Create Survey</a></li>
        <li><a href="{% url 'admin-panel' %}">View Survey Data</a></li>
      </ul>
    </div>
  </div>
  <div class= "centerdv container">
    <div class="page-header">
      <h2>Create a new Survey</h2>
    </div>
    <br>
    <form method= "post" class = "centerform" action = {% url 'admin-survey-create' %}>
      {% csrf_token %}
      <b>Survey Title:</b>
      <input type = "text" class = "form-control" name = "survey-title">
      <br>
      <input type = "submit" class = "btn btn-primary" value = "Add Questions"> 
    </form> 
    
  </div>  
</body>
</html> 

simplesurvey/survey/templates/survey-take.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  
  </style>
  <div class = "jumbotron container centerdv">
    <h2>{{survey.title}}</h2>
  </div>
  <form method = "post" action = {% url 'fill-survey' %}>
    <input type = "hidden" name = "survey_id" value = {{survey.id}}>
    {% csrf_token %}
    {% for question in questions %}
    <div class = "container centerdv">
      <div class = "well centerdv">
        <b>{{question.question_text}}</b>
      </div>
      {% for choice in question.choice_set.all %}
      <label class = "radio inline">
        <input type = "radio" name="question{{question.id}}" value= {{choice.id}}>
        {{choice.choice_text}}
      </label>
      {% endfor %}
    {% endfor %} 
    <input type = "submit" value = "Complete!" class = "btn btn-lg btn-success"> 
    </div>
  </form>
  
</body>
</html>

simplesurvey/survey/templates/surveynotfound-error.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <style type = "text/css">
  .centerdv{
    margin-top: 5%;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
  }
  
  </style>
  <div class="jumbotron container centerdv">
    <h1>Survey # {{sv_id}} does not exist </h1>
  </div>
</body>
</html>